- name: Update package cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install Node.js
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Install npm
  become: true
  ansible.builtin.apt:
    name: npm
    state: present

- name: Install jq
  become: true
  ansible.builtin.apt:
    name: jq
    state: present

- name: Install git
  become: true
  ansible.builtin.apt:
    name: git
    state: present


- name: Install pip
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present
