- name: add The platform to the file /ect/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: $IP_Platfrom $IP_Url
    state: present
    create: yes

#this line should be like this per example
# line: 192.168.84.2  learn.zone01kisumu.ke