- name: install passlib
  become: true
  pip:
    name: passlib
    state: present

- name: Change the user bocal password
  become: true
  user:
    name: bocal
    update_password: always
    password: "{{ newpassword|password_hash('sha512') }}"
