- name: remove previous go
  become: true
  ansible.builtin.apt:
    name: golang-go
    state: absent

- name: remove /etc/source.list.d/golang.list
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/golang.list
    state: absent

- name: Download the Go binary
  get_url:
    url: https://dl.google.com/go/go1.22.1.linux-amd64.tar.gz
    dest: /tmp/go.tar.gz
    mode: 0755

- name: Extract the Go binary
  archive:
    path: /tmp/go.tar.gz

- name: Set Go environment variables
  lineinfile:
    path: ~/.bashrc
    line: 'export GOROOT=/usr/local/go'
    state: present
  lineinfile:
    path: ~/.bashrc
    line: 'export GOPATH=$HOME/go'
    state: present
