
- name: Allow incoming SSH traffic on port 22
  become: true 
  shell: iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT

- name: Allow outgoing SSH traffic on port 22
  become: true 
  shell: iptables -A OUTPUT -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT

- name: Allow outgoing traffic to a specific destination
  become: true 
  shell: iptables -A OUTPUT -d learn.zone01kisumu.ke -j ACCEPT

- name: Drop all outgoing traffic
  become: true 
  shell: iptables -A OUTPUT -j DROP
  
- name: Save iptables rules
  become: true
  ansible.builtin.shell: 
    cmd: iptables-save 

# - name: Save iptables rules
#   become: true
#   ansible.builtin.shell: 
#     cmd: iptables-save > /etc/iptables/rules.v4
