- name: Debug current user
  become: true
  debug:
    msg: "Current user is {{ ansible_user }}"

- name: Add sudoers entry to restrict network settings
  become: true
  lineinfile:
    dest: /etc/sudoers
    line: " ALL=(ALL:ALL) /usr/sbin/network-manager, /bin/ip"
    validate: 'visudo -cf %s'
  when: "'bocal' in (ansible_user | password_hash('sha512'))"
