- name: Add bocal members public keys to the bocal user
  tags: [ssh]
  loop: "{{ extra_ssh_keys }}"
  ansible.builtin.lineinfile:
    path: /home/bocal/.ssh/authorized_keys
    line: "{{ item }}"
    state: present
